uploads = []
generated = []

[[outputs]]
id = "B9_XAUn_cdonMdo-1-tUI"
uri = "file://api-portal.tar.gz"
type = "unspecified"
title = "Full Project Archive (source + PostgreSQL DB backup)"

[[outputs]]
id = "eWUZ0QqSeQN3WrzuAgztA"
uri = "file://README.md"
type = "text"
title = "README — Local Install & Deploy Guide"
