// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/api-portal/AdminPanel.tsx": () => import("../components/mockups/api-portal/AdminPanel.tsx"),
  "./components/mockups/api-portal/ApiDocs.tsx": () => import("../components/mockups/api-portal/ApiDocs.tsx")
};
